name: 'CAPM'
description: 'Code Analysis Package Manager 📦'
branding:
  icon: 'activity'
  color: 'green'
inputs:
  capm_version:
    description: 'CAPM version'
    required: false
    default: 'latest'
runs:
  using: 'node20'
  main: 'dist/index.js'
inputs:
  token:
    description: 'GitHub token for storing results'
    required: false
    default: ${{ github.token }}
  capm_version:
    description: 'CAPM version'
    required: false
    default: 'latest'
